# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/jaz/bin/cmake-3.29.3-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/jaz/bin/cmake-3.29.3-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/A6A00642A0061A07/G-Drive/2025/cvut/elmag/zkouska/mma

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/A6A00642A0061A07/G-Drive/2025/cvut/elmag/zkouska/mma

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/home/jaz/bin/cmake-3.29.3-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/jaz/bin/cmake-3.29.3-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/jaz/bin/cmake-3.29.3-linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/jaz/bin/cmake-3.29.3-linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/jaz/bin/cmake-3.29.3-linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/jaz/bin/cmake-3.29.3-linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/jaz/bin/cmake-3.29.3-linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/jaz/bin/cmake-3.29.3-linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/A6A00642A0061A07/G-Drive/2025/cvut/elmag/zkouska/mma/CMakeFiles /mnt/A6A00642A0061A07/G-Drive/2025/cvut/elmag/zkouska/mma//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/A6A00642A0061A07/G-Drive/2025/cvut/elmag/zkouska/mma/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mma

# Build rule for target.
mma: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mma
.PHONY : mma

# fast build rule for target.
mma/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mma.dir/build.make CMakeFiles/mma.dir/build
.PHONY : mma/fast

#=============================================================================
# Target rules for targets named test_mma

# Build rule for target.
test_mma: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mma
.PHONY : test_mma

# fast build rule for target.
test_mma/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_mma.dir/build.make CMakeFiles/test_mma.dir/build
.PHONY : test_mma/fast

#=============================================================================
# Target rules for targets named matio

# Build rule for target.
matio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 matio
.PHONY : matio

# fast build rule for target.
matio/fast:
	$(MAKE) $(MAKESILENT) -f matio/CMakeFiles/matio.dir/build.make matio/CMakeFiles/matio.dir/build
.PHONY : matio/fast

#=============================================================================
# Target rules for targets named matdump

# Build rule for target.
matdump: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 matdump
.PHONY : matdump

# fast build rule for target.
matdump/fast:
	$(MAKE) $(MAKESILENT) -f matio/CMakeFiles/matdump.dir/build.make matio/CMakeFiles/matdump.dir/build
.PHONY : matdump/fast

#=============================================================================
# Target rules for targets named test_mat

# Build rule for target.
test_mat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mat
.PHONY : test_mat

# fast build rule for target.
test_mat/fast:
	$(MAKE) $(MAKESILENT) -f matio/CMakeFiles/test_mat.dir/build.make matio/CMakeFiles/test_mat.dir/build
.PHONY : test_mat/fast

#=============================================================================
# Target rules for targets named test_snprintf

# Build rule for target.
test_snprintf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_snprintf
.PHONY : test_snprintf

# fast build rule for target.
test_snprintf/fast:
	$(MAKE) $(MAKESILENT) -f matio/CMakeFiles/test_snprintf.dir/build.make matio/CMakeFiles/test_snprintf.dir/build
.PHONY : test_snprintf/fast

lib.o: lib.cu.o
.PHONY : lib.o

# target to build an object file
lib.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mma.dir/build.make CMakeFiles/mma.dir/lib.cu.o
.PHONY : lib.cu.o

lib.i: lib.cu.i
.PHONY : lib.i

# target to preprocess a source file
lib.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mma.dir/build.make CMakeFiles/mma.dir/lib.cu.i
.PHONY : lib.cu.i

lib.s: lib.cu.s
.PHONY : lib.s

# target to generate assembly for a file
lib.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mma.dir/build.make CMakeFiles/mma.dir/lib.cu.s
.PHONY : lib.cu.s

mmaOpt.o: mmaOpt.cpp.o
.PHONY : mmaOpt.o

# target to build an object file
mmaOpt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mma.dir/build.make CMakeFiles/mma.dir/mmaOpt.cpp.o
.PHONY : mmaOpt.cpp.o

mmaOpt.i: mmaOpt.cpp.i
.PHONY : mmaOpt.i

# target to preprocess a source file
mmaOpt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mma.dir/build.make CMakeFiles/mma.dir/mmaOpt.cpp.i
.PHONY : mmaOpt.cpp.i

mmaOpt.s: mmaOpt.cpp.s
.PHONY : mmaOpt.s

# target to generate assembly for a file
mmaOpt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mma.dir/build.make CMakeFiles/mma.dir/mmaOpt.cpp.s
.PHONY : mmaOpt.cpp.s

mmaOpt.o: mmaOpt.cu.o
.PHONY : mmaOpt.o

# target to build an object file
mmaOpt.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mma.dir/build.make CMakeFiles/mma.dir/mmaOpt.cu.o
.PHONY : mmaOpt.cu.o

mmaOpt.i: mmaOpt.cu.i
.PHONY : mmaOpt.i

# target to preprocess a source file
mmaOpt.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mma.dir/build.make CMakeFiles/mma.dir/mmaOpt.cu.i
.PHONY : mmaOpt.cu.i

mmaOpt.s: mmaOpt.cu.s
.PHONY : mmaOpt.s

# target to generate assembly for a file
mmaOpt.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mma.dir/build.make CMakeFiles/mma.dir/mmaOpt.cu.s
.PHONY : mmaOpt.cu.s

test_suits.o: test_suits.cpp.o
.PHONY : test_suits.o

# target to build an object file
test_suits.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_mma.dir/build.make CMakeFiles/test_mma.dir/test_suits.cpp.o
.PHONY : test_suits.cpp.o

test_suits.i: test_suits.cpp.i
.PHONY : test_suits.i

# target to preprocess a source file
test_suits.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_mma.dir/build.make CMakeFiles/test_mma.dir/test_suits.cpp.i
.PHONY : test_suits.cpp.i

test_suits.s: test_suits.cpp.s
.PHONY : test_suits.s

# target to generate assembly for a file
test_suits.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_mma.dir/build.make CMakeFiles/test_mma.dir/test_suits.cpp.s
.PHONY : test_suits.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... matdump"
	@echo "... matio"
	@echo "... mma"
	@echo "... test_mat"
	@echo "... test_mma"
	@echo "... test_snprintf"
	@echo "... lib.o"
	@echo "... lib.i"
	@echo "... lib.s"
	@echo "... mmaOpt.o"
	@echo "... mmaOpt.i"
	@echo "... mmaOpt.s"
	@echo "... mmaOpt.o"
	@echo "... mmaOpt.i"
	@echo "... mmaOpt.s"
	@echo "... test_suits.o"
	@echo "... test_suits.i"
	@echo "... test_suits.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

